### ISSUE TITLE
Unablt to install Ipfsecret

### ISSUE THREAD

**Issue by LogeswaranAudhikesavan** [c2fo-lab/ipfsecret#4]
Hi - 

Very glad that we have an option to set passphrase before uploading, but unable to install this module. I am using following modules
npm -> 5.6.0
node -> 8.11.3

Getting following issue, while installing npm install ipfsecret --save

    fsStat = util.promisify(fs.stat),
                  ^

TypeError: util.promisify is not a function
    at Object.<anonymous> (/home/zuiver/InfiLokr_Complete/Production/infilokr_pgp/client/node_modules/ipfsecret/bin/ipfsecret.js:15:19)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
Error: api not running
Error: context canceled

/home/zuiver/InfiLokr_Complete/Production/infilokr_pgp/client/node_modules/ipfsecret/bin/get-fonts.js:9
    { URL } = require('url'),
    ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

Any workaround?. I ensured that, util, fs modules are installed.

**Comment by petethomas** [comment]
Hi Logeswaran, 

node 8.11.3 & npm 5.6.0 are together working OK here locally, i.e., I just stepped through the commands and output at the end of this comment without issue.  

It may be that you are not actually attempting the install using node 8.11.3, despite operating under the assumption that you are.  I point this out because starting with node 8.0.0, [```promisify()``` should work fine](https://nodejs.org/en/blog/release/v8.0.0/).

As for the second error, ```SyntaxError: Unexpected token {```, my suspicion is again related to your local environment being different than assumed, and that once you correct this, this error will go away.  Please see [this post](https://medium.com/the-node-js-collection/an-update-on-es6-modules-in-node-js-42c958b890c) (But it works in Babel!) for more information.  ipfsecret installation currently relies on the proper functioning of [babel](https://babeljs.io/en/setup/#installation) in order to complete and the environment under which you're currently running, for whatever reason, isn't detecting babel.

Are you by chance running Windows for this install?  If so we haven't yet tested with that operating system.  You might want to check out [this issue from an unrelated project](https://github.com/coryhouse/react-slingshot/issues/400#issuecomment-290497767), posted last year.

Hope this helps.

```
λ pwd
/Users/pete/test
λ uname -a
Darwin Petes-MacBook-Pro.local 15.6.0 Darwin Kernel Version 15.6.0: Mon Nov 13 21:58:35 PST 2017; root:xnu-3248.72.11~1/RELEASE_X86_64 x86_64
λ ipfs daemon &
[...]
λ git clone git@github.com:c2fo-lab/ipfsecret.git
Cloning into 'ipfsecret'...
remote: Counting objects: 128, done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 128 (delta 4), reused 10 (delta 3), pack-reused 114
Receiving objects: 100% (128/128), 202.91 KiB | 0 bytes/s, done.
Resolving deltas: 100% (47/47), done.
λ cd ipfsecret/
λ node -v && npm -v
v8.11.3
5.6.0
λ npm install
[...]
λ npm run test

> ipfsecret@0.1.4 test /Users/pete/test/ipfsecret
> mocha --timeout 10000 --reporter spec

  ipfsecret.addIndexed
    ✓ Loads expected CSS files
    ✓ Loads expected JavaScript files
    ✓ Loads expected font files
    ✓ Generates expected HTML indices (70ms)
    ✓ Generates expected HTML index content (41ms)
    ✓ Throws error with no passphrase
    ✓ Returns expected number of objects
    ✓ Returns expected object format
    ✓ Accepts a directory
    ✓ Detects passphrase inside Wcrypt options (39ms)
    ✓ Detects passphrase outside Wcrypt options
    ✓ Accepts valid custom Wcrypt options
    ✓ Rejects invalid custom Wcrypt options
    ✓ Rejects non-string path
    ✓ Respects root option
    ✓ Respects directory name option (41ms)
    ✓ Respects suffix option (42ms)
    ✓ Creates correct relative links (40ms)
    ✓ Correctly includes hidden files

  ipfsecret.add
    ✓ Throws error with no passphrase
    ✓ Returns expected object format
    ✓ Returns encrypted data
    ✓ Accepts a directory
    ✓ Detects passphrase inside Wcrypt options
    ✓ Detects passphrase outside Wcrypt options (57ms)
    ✓ Accepts valid custom Wcrypt options (65ms)
    ✓ Rejects invalid custom Wcrypt options (file)
    ✓ Rejects non-string path
    ✓ Respects root option (42ms)
    ✓ Respects directory name option
    ✓ Respects suffix option
    ✓ Correctly includes hidden files (40ms)

  ipfsecret.get
    ✓ Rejects numeric multihash
    ✓ Accepts multihash as buffer
    ✓ Accepts multihash as string
    ✓ Returns a readable stream
    ✓ Returns expected number of objects
    ✓ Returns expected decrypted data

  Version
    ✓ Equals package.json.version

  Debug (child_process)
    ✓ Sends output to stderr (345ms)


  40 passing (1s)
```
